## PROG8245 Assignment 1: (Total Marks 100)
## Start on 16th of September- Due on 27th of September

- TODO: write your name and ID below
- Name:
- ID:
- Kindly note that this assignment is to be solved by yourself, without the use of AI and chatbots.
- If chatbot usage is detected, the penalty that is discussed in Week 1 slides will apply.
- Each code block will have a Todo comment which explains the functionality, expected input, and expected output of the function.
- There are 10 marks in this assignment for assuring that the code couldn't be broken (no errors can be thrown, please consider mathematical and logical errors)
- There are 10 marks in this assignment for commenting and code readability.


### Part 1: Python Basics

#### Question 1:

In [277]:

def total_price(price, tax):
    # 3 marks
    # TODO: write the functionality of the code where
    #  you are taking as an input a price of an item and the
    #  tax in decimal (13% tax will be given as 0.13),
    #  you should return the taxedPrice of that item
    #  which will be the total price after tax a customer must pay
    # (The price of the item plus the applicable taxes)
    tax_value = price * tax
    taxed_price = tax_value + price
    #If you dont want to round the value uncomment the below line
    #return taxed_price
    return round(taxed_price, 2)

# Test
assert total_price(10,.13) == 11.3
assert total_price(10,0) == 10
assert total_price(10,1) == 20
assert total_price(10,10) == 110
assert total_price(0,1) == 0
assert total_price(0,0) == 0
assert total_price(1,-1) == 0



#### Question 2:

In [278]:
def divisible_by(x, y):
    # 3 marks
    # TODO: write a function that returns True if x is divisible by y,
    #  and returns False OTHERWISE (all other cases).
    try:
        if(x%y == 0):
            return True
        else:
            return False
    except:
        return False
    
#Test
assert divisible_by(10,3) == False
assert divisible_by(10,5) == True
assert divisible_by(10,0) == False
assert divisible_by(0,0) == False
assert divisible_by(5,10) == False

#### Question 3:

In [279]:
def basic_calculator(x, y, operator):
    # 5 marks
    # TODO: write the functionality of the code where you are
    #  coding a basic calculator that performs basic addition "+", subtraction "-",
    #  multiplication "*", division "/", modulus "%" and integer division "//"
    #  the function must apply the operator to x and y for example:
    #  basicCalculator(10, 15, "*") should apply 10*15 and save it to the result variable
    #  NOTE: YOU NEED TO HANDLE DIVISION ERRORS BY RETURNING A STRING WITH THE WORD "error"
    #  NOTE: YOU NEED TO HANDLE AN INVALID OPERATOR BY RETURNING A STRING HAVING THE WORD "invalid"
    try:
        match(operator):
            case '+':
                return x + y
            case '-':
                return x - y
            case '*':
                return x * y
            case '/':
                return x / y
            case '//':
                return x // y
            case '%':
                return x % y
            case _:
                return 'invalid'
    except:
        return 'error'


#Test
assert basic_calculator(0,0,'+') == 0
assert basic_calculator(0,1,'+') == 1
assert basic_calculator(1,0,'+') == 1
assert basic_calculator(0,-1,'+') == -1
assert basic_calculator(0,-1,'-') == 1
assert basic_calculator(-1,-1,'-') == 0
assert basic_calculator(1,-1,'-') == 2
assert basic_calculator(1,0,'-') == 1
assert basic_calculator(0,0,'/') == 'error'
assert basic_calculator(0,0,'//') == 'error'
assert basic_calculator(0,0,'*') == 0
assert basic_calculator(0,0,'%') == 'error'
assert basic_calculator(10,0,'/') == 'error'
assert basic_calculator(10,0,'%') == 'error'
assert basic_calculator(10.5,5.25,'/') == 2
assert basic_calculator(10, 3, '//') == 3
assert basic_calculator(10, 10, '**') == 'invalid'


#### Question 4:

In [280]:
def sum_of_even(numbers_list):
    # 3 marks
    # TODO: write the functionality of the code where you are
    # taking as an input a list of numbers
    # returning the sum of even numbers in the list
    # NOTE: YOU NEED TO HANDLE ERRORS OF GIVING LIST OF STRINGS OR/AND
    #  STRINGS WITH NUMBERS by returning "invalid"
    # sum_of_even([1,2,3,4,5,6]) = 12
    try:
        sum = 0
        for num in numbers_list:
            if(num % 2 == 0):
                sum += num
        return sum
    except:
        return 'invalid'
    

assert sum_of_even([1,2,3,4,5,6]) == 12
assert sum_of_even([1,1,1,'true']) == 'invalid'
assert sum_of_even([1,1,1,2]) == 2
assert sum_of_even([]) == 0
assert sum_of_even([2,-2,1,-1,-4]) == -4
assert sum_of_even([2,-2,1,-1,-4,-8]) == -12
assert sum_of_even([2,-2,1,-1,-4,'-8']) == 'invalid'

#### Question 5:

In [281]:
def reverse_string(input_string):
    # 3 marks
    # TODO: write the functionality of the code where you are
    # taking as an input a string
    # returns the reverse of the string
    # reverse_string("hello") = "olleh"
    # NOTE: Numbers should be handled as strings ex: 123 returns "321"
    if(isinstance(input_string, str)):
        input = input_string
    elif(isinstance(input_string, int) or isinstance(input_string, float)):
        input = str(input_string)
    else:
        return 'invalid' #Could be any object or other types other than string, int or float
    return input[::-1]

assert reverse_string('nikhil') == 'lihkin'
assert reverse_string(123) == '321'
assert reverse_string(1) == '1'
assert reverse_string('') == ''
assert reverse_string('1223') == '3221'
assert reverse_string(123.90) != '09.321' ## This is failing. Reason being python automatically trims float to the highest precision value. So in this case 123.9 is how python passes the value
assert reverse_string(123.90) == '9.321' ## This is why this asssertion works. ^
assert reverse_string(123.91) == '19.321'
assert reverse_string([1,2,3]) == 'invalid' # in case of object invalid willl be returned.

#### Question 6:

In [282]:
def diamond_string(length):
    # 5 marks
    # TODO: write the functionality of the code where you are
    # taking as an input a POSITIVE ODD length
    # saves in a string the diamond as follows:
    # diamond_string(5)
    #   *
    #  ***
    # *****
    #  ***
    #   *
    # NOTE: The input must be positive odd, if not return empty string ""  
    result = "" 
    if(isinstance(length, int) and length % 2 == 1 and length > 0):
        for i in range(length):
            starcount = (i)*2 + 1 if (i)*2 + 1 - length <= 0 else (length-i)*2 - 1
            for s in range(length-starcount//2):
                result += " "
            for star in range(starcount):
                result += "*"
            for s in range(length-starcount//2):
                result += " "
            result += '\n'
    else:
        return ""
    return result
    
print(diamond_string(11))



           *           
          ***          
         *****         
        *******        
       *********       
      ***********      
       *********       
        *******        
         *****         
          ***          
           *           



#### Question 7:

In [283]:
def longest_consecutive_subarray(number_array):
    # 8 marks
    # TODO: write the functionality of the code where you are
    # taking as an input an array of REAL NUMBERS
    # return the length of the longest subarray that could be
    # built using the input
    # longest_consecutive_subarray([100, 4, 200, 1, 3, 2]) = 4
    # Function should return 4 which represents in this case
    # the longest_consecutive_subarray that could be built [1,2,3,4]
    # You can't use Built in Sorting!
    # Note: - If any error exists in the input, "error" should be returned
    #       - The difference between any 2 consecuetive numbers is 1.

    # using set to remove duplicates
    number_set = set()
    number_set.update(number_array)
    #inefficient approach
    # finding max and min value 
    # We start from the lowest number in the set 
    #and iterate till the max value. While doing this
    # check presence in the set and increment count.
    # This is iterating from min to max which is inefficient eg in [1,2,200001,200002]
    # mx = max(number_set)
    # mn = min(number_set)
    # longest_count = 0
    # for i in range(mn, mx+1):
    #     if i in number_set:
    #         temp_count = 1
    #         for j in range(i+1, mx+1):
    #             if j in number_set:
    #                 temp_count+=1
    #             else: 
    #                 break
    #         longest_count = max(longest_count, temp_count)
    # better approach
    longest_count = 0
    for num in number_set:
        temp_count = 1
        if num-1 not in number_set:
            while(num+1 in number_set):
                temp_count+=1
                num+=1
        longest_count = max(longest_count, temp_count)
    return longest_count

assert longest_consecutive_subarray([1,2,3,3,3,3,20,21,22,23,24,25,26,27,28,29,100,101,102,103,104]) == 10
assert longest_consecutive_subarray([1,2,3]) == 3
assert longest_consecutive_subarray([1,0,-1,-2,-3,-4,-5,-6,-5,-5,-5]) == 8

#### Question 8 (Challenging):

In [294]:
def can_be_segmented(input_string, word_dict):
    # 15 marks
    # TODO: Write the functionality of the code where you
    # are given as an input a string and a word_dict
    # Your target is to return True, if input_string can be segmented
    # (broken-down) into a sequence of one or more dictionary words
    # otherwise return False
    # Sample Input: can_be_segmented("applepenapple", {'apple','pen'}) ==> True
    # Sample Input: can_be_segmented("catsandog", {'cats','dog','sand','and','cat'}) ==> False
    # Hint: You can start by checking which prefix exist in the dictionary, and call the same function recursively
    # on the remaining string.
    # Handling edge case of input string being empty
    if len(input_string) == 0:
        return True
    return rec_check_prefix(input_string[:1], input_string[1:], word_dict)

def rec_check_prefix(current_word, input_string, word_dict): 
    #print(f'cWord: {current_word} input: {input_string}')
    # if current word that is prefix is inside the dictionary then 
    # in the next recursive call we trim the prefix from input string
    # and pass the first letter from the remaining input_string to 
    # the next iterative call. 
    if(current_word in word_dict):
        prefix_removed_string = input_string.removeprefix(current_word)
        # if in case after removing prefix the input string is empty 
        # this means that we have succesfully found that the input string
        # can be created with words inside the dictionary. hence we return true.
        if(len(prefix_removed_string) == 0):
            return True
        #print(f'removed {removed}  {removed[:1]}   {removed[1:]}')
        # Important :: Here we need to keep calling the recursive function
        # without removing the prefix. eg In case of "cat" and "cats" and lets say 
        # dictionary contains both words if we just remove "cat" and check for result 
        # it means that we are not really checking if it was possible to create 
        # the string using "cats". So we check the result from "cat" If its true then well and good.
        # We might be able to create the string using "cats" also but we just need to figure out if
        # a single such solution is available or not. That is the reason for having the if condition.
        result = rec_check_prefix(prefix_removed_string[:1], prefix_removed_string[1:], word_dict)
        if result:
            return True
        else:
            return rec_check_prefix(current_word+input_string[:1], input_string[1:], word_dict)
    #If input string is empty and current word is not in the dictionary it means 
    # we were not able to create the input word succesfully from dictionary.
    elif len(input_string) == 0:
        return False
    # This is the last condition where we just take one letter from input string and append into 
    # current word and repeat the recursive calls.
    else:
        #print(f'current {current_word} {current_word+input_string[:1]} {input_string[1:]}')
        return rec_check_prefix(current_word+input_string[:1], input_string[1:], word_dict)


assert can_be_segmented("catsanddogcat", {'cats','dog','sand','and','cat'}) == True
assert can_be_segmented("a", {'a','dog','sand','and','cat'}) == True
assert can_be_segmented("abcabc", {'a','b','cab','d','dog','sand','and','cat'}) == False
assert can_be_segmented("", {'a','b','cab','d','dog','sand','and','cat'}) == True
assert can_be_segmented("baaacab", {'aa','b','acab','d','dog','sand','and','cat'}) == True
assert can_be_segmented("baaacab ", {'aa','b','acab','d','dog','sand','and','cat'}) == False
assert can_be_segmented("baaacab ", {'aa','b','acab','d','dog','sand','and','cat', " "}) == True
assert can_be_segmented("applepenapple", {'apple','pen'}) == True






### Part 2: Numpy Basics: 
- In this Part of the assignment, you are <b>ONLY ALLOWED</b> to use Numpy and its functions. 
- You are not expected to use Loops.

In [285]:
import numpy as np

#### Question 9:

In [286]:
def no_zeros(array_input):
    # 3 marks
    ## TODO: This function should return True if 
    ## numpy array arrayInput does not contain any zero
    ## and will return False otherwise.
    ## Implement this function using ONLY numpy methods
    ## Sample input: np.array([1,2,3,4,5,6,0]) Sample Output: False
    ## Sample input: np.array([1,2,3,4,5,6]) Sample Output: True
    return np.any(array_input==0) == False

assert no_zeros(np.array([1,2,3,4,56,0])) == False
assert no_zeros(np.array([0,0,0])) == False
assert no_zeros(np.array([1])) == True



#### Question 10:

In [287]:
def two_dimensions(n):
    # 7 marks
    ## TODO: This function should create a 2d Array of shape n*n for any positive number
    ## Where the borders of the array are ones
    ## all other elements are zero
    ## Implement this function using ONLY numpy methods
    ## Sample input 3
    ## sample output [[1,1,1],[1,0,1],[1,1,1]]
    # define top array
    if isinstance(n, int) == False:
        return 'error'
    if n == 1:
        return np.ones(1)
    elif n == 2:
        return np.ones((2,2))
    elif n > 2:
        arr_top = np.ones(n-2)
        #define bottom array
        arr_bottom = np.ones(n-2)
        #define leftmost vertical column
        arr_left = np.ones((n,1))
        #define rightmost vertical column
        arr_right = np.ones((n,1))
        #define part of matrix wich has only zeros
        arr_zeros = np.zeros((n-2,n-2))
        #vertically stack top zero array and bottom array
        vstack_array = np.vstack((arr_top, arr_zeros, arr_bottom))
        #horizontally stack vertically stcked array and left and right columns
        hstack_array = np.hstack((arr_left, vstack_array, arr_right))
        return hstack_array
    else:
        return 'error'


print(two_dimensions(7))
    

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


#### Question 11:

In [288]:
def random_generation(n,min,max):
    # 5 marks
    # TODO: Write a function that takes as an input
    # Dimension of 2d Array n, min and max
    # Generate an n*n array with random numbers between
    # min and max inclusive
    # Such that no element is duplicated
    # return numpy array
    # Implement this function using ONLY numpy methods
    # Sample Input: random_generation(3,0,12) --> [[4,2,6],[1,5,11],[10, 3,9]]
    if max - min + 1 < n*n:
        return 'Cant be filled by random numbers since enough unique numbers are not available'
    arr = np.random.choice(np.arange(min, max+1), size=(n, n), replace = False)
    return arr

print(random_generation(5, 1, 25))

[[ 5 20  1 15 18]
 [16  3 19 11  2]
 [14 17 12 21 13]
 [ 9 10  8 25  6]
 [23 22  7  4 24]]


#### Question 12:

In [289]:
def matrix_border_sum(matrix):
    # 8 marks
    # TODO: Write a function that takes as an input a matrix
    # and return the sum of all elements in the borders
    # Implement this function using ONLY numpy methods
    # Sample Input: np.array([[1,2,3],
    #                         [4,5,6],
    #                         [7,8,9]])
    # Output: matrix_border_sum(matrix) =  1+2+3+4+6+7+8+9 = 40
    if matrix.ndim == 1:
        return np.sum(matrix)
    (row, column) = matrix.shape
    if row == 1 or column ==1:
        return np.sum(matrix)
    arr_top = matrix[0, :]
    arr_bottom = matrix[-1, :]
    arr_left = matrix[1:-1, 0]
    arr_right = matrix[1:-1, -1]
    sum = np.sum(arr_top) +np.sum(arr_bottom) + np.sum(arr_left) + np.sum(arr_right)
    return sum

assert matrix_border_sum(np.array([[1,2,3],
                             [4,5,6],
                             [7,8,9]])) == 40
assert matrix_border_sum(np.array([[1,2,3,4],[2,2,3,4],[3,2,3,4]])) == 28
assert matrix_border_sum(np.array([[1,2,3],[2,2,3],[3,2,3]])) == 19
assert matrix_border_sum(np.array([1,2,3,3,2,1])) == 12
assert matrix_border_sum(np.array([1,2,3,3,2,1,10])) == 22




### Part 3: Pandas

In [290]:
import pandas as pd

#### Question 13 (12 marks): 
- Using RegularSeasonCompactResults.csv and Teams.csv apply the following functionalities

In [291]:
# Using RegularSeasonCompactResults.csv
# 1- Create a filter to show if there are any draw matches
# 2- Apply the filter to the dataframe
# 3- SHOW/PRINT the dataframe length or count (4 marks)
## TODO: Your code should be here
df = pd.read_csv('RegularSeasonCompactResults.csv')
# From the column name we understand that Wscore and Lscore can be Win score and lose score.
# To create a filter for draw we check if there are columns with wscore and lscore equal to each other.
filter_draw = df['Wscore'] == df['Lscore']
df_draw = df[filter_draw]
print(f'Number of Matches drawn : {len(df_draw)}')


Number of Matches drawn : 0


In [292]:
# Using RegularSeasonCompactResults.csv
# 1- Create a filter showing the entries where the winningteamID= 1400- (last two digits of your id)
# 2- Create another filter for the season of 2013
# 3- Apply the filter to the dataframe
# 4- Show the resulted dataframe (4 marks)
# (Example: IF your id is 8000021, the winning team id = 1400-21= 1379)
# TODO: Your code should be here
#team id = 1400 - 54  (90262"54")
team_id_filter = df['Wteam'] == 1346 
season_2013_filter = df['Season'] == 2013
result_df = df[team_id_filter & season_2013_filter]
print(f'Details of matches won by team 1346 in 2013 season')
display(result_df)


Details of matches won by team 1346 in 2013 season


Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
123993    2013       5   1346      65   1216      61    A      0
124249    2013      11   1346      98   1233      92    N      1
125093    2013      30   1346      67   1159      56    H      0
125574    2013      46   1346      59   1107      57    A      0
126124    2013      61   1346      82   1254      74    H      0
126639    2013      73   1346      75   1384      66    A      1
126964    2013      80   1346      85   1148      78    H      0
127091    2013      82   1346      58   1192      56    H      0
127419    2013      89   1346      74   1447      69    A      0
127599    2013      94   1346      79   1284      63    H      0
127927    2013     101   1346      63   1352      61    H      0
128056    2013     103   1346      71   1384      55    H      0
128247    2013     108   1346      81   1357      74    A      0
128361    2013     110   1346      69   1136      58    H      0
128553    2013     115   1346      78   1383      67    A      0

In [293]:
# Using RegularSeasonCompactResults.csv & Teams.csv
# 1- Load and merge both dataframes
# 2- Where the merge is on WinningTeamId (RegularSeasonCompactResults) and TeamId (Teams.csv)
# 3- Name the dataframe: DFCombined
# 4- Show the top 3 rows (4 marks)
# TODO: Your code should be here
# Reading teams csv
df_teams = pd.read_csv('Teams.csv')
# Merging Based on team id using left join
merged_df = pd.merge(df, df_teams, left_on='Wteam', right_on='Team_Id', how='left')
# Dropping duplicate column
merged_df = merged_df.drop(columns='Team_Id')
display(merged_df.head(3))

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot   Team_Name
0    1985      20   1228      81   1328      64    N      0    Illinois
1    1985      25   1106      77   1354      70    H      0  Alabama St
2    1985      25   1112      63   1223      56    H      0     Arizona